version: '3'
name: mangas-api
services:
  server:
    container_name: mangas-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
      - ./certificates:/app/certificates
    expose:
      - '${PORT}'
